# Generated by Django 6.1 on 2026-08-22 05:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0002_initial'),
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('activity_order', models.PositiveIntegerField(default=1, help_text='Order of this activity within the day.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_usages', to='activities.activity')),
            ],
            options={
                'verbose_name': 'Trip Activity',
                'verbose_name_plural': 'Trip Activities',
                'db_table': 'trip_activities',
                'ordering': ['trip_stop', 'activity_date', 'activity_order'],
            },
        ),
        migrations.CreateModel(
            name='TripStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('stop_order', models.PositiveIntegerField(default=1, help_text='Sequence of this stop in the trip.')),
                ('transport_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('accommodation_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_stops', to='destinations.city')),
            ],
            options={
                'verbose_name': 'Trip Stop',
                'verbose_name_plural': 'Trip Stops',
                'db_table': 'trip_stops',
                'ordering': ['trip', 'stop_order'],
            },
        ),
    ]
