# Generated by Django 6.1 on 2026-08-22 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('itinerary', '0001_initial'),
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripstop',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='trips.trip'),
        ),
        migrations.AddField(
            model_name='tripactivity',
            name='trip_stop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_activities', to='itinerary.tripstop'),
        ),
        migrations.AddIndex(
            model_name='tripstop',
            index=models.Index(fields=['trip', 'stop_order'], name='idx_stop_trip_order'),
        ),
        migrations.AddIndex(
            model_name='tripstop',
            index=models.Index(fields=['city'], name='idx_stop_city'),
        ),
        migrations.AddConstraint(
            model_name='tripstop',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='ck_stop_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='tripstop',
            constraint=models.CheckConstraint(condition=models.Q(('transport_cost__gte', 0)), name='ck_stop_transport_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='tripstop',
            constraint=models.CheckConstraint(condition=models.Q(('accommodation_cost__gte', 0)), name='ck_stop_accommodation_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='tripstop',
            constraint=models.UniqueConstraint(fields=('trip', 'stop_order'), name='uq_stop_trip_order'),
        ),
        migrations.AddIndex(
            model_name='tripactivity',
            index=models.Index(fields=['trip_stop', 'activity_date', 'activity_order'], name='idx_tripact_stop_date_order'),
        ),
        migrations.AddConstraint(
            model_name='tripactivity',
            constraint=models.UniqueConstraint(fields=('trip_stop', 'activity', 'activity_date'), name='uq_tripact_stop_activity_date'),
        ),
        migrations.AddConstraint(
            model_name='tripactivity',
            constraint=models.CheckConstraint(condition=models.Q(('estimated_cost__gte', 0)), name='ck_tripact_cost_non_negative'),
        ),
    ]
