# Generated by Django 6.1 on 2026-08-22 05:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(db_index=True, max_length=100)),
                ('region', models.CharField(blank=True, db_index=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('image', models.URLField(blank=True, max_length=500)),
                ('cost_index', models.PositiveSmallIntegerField(default=3, help_text='Cost level 1 (cheapest) to 5 (most expensive).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('popularity_score', models.DecimalField(decimal_places=2, default=0, help_text='Popularity rating 0.0 to 10.0.', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
                'db_table': 'cities',
                'ordering': ['-popularity_score', 'name'],
                'indexes': [models.Index(fields=['name'], name='idx_city_name'), models.Index(fields=['-popularity_score'], name='idx_city_popularity')],
                'constraints': [models.UniqueConstraint(fields=('name', 'country'), name='uq_city_name_country')],
            },
        ),
        migrations.CreateModel(
            name='SavedCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='destinations.city')),
            ],
            options={
                'verbose_name': 'Saved City',
                'verbose_name_plural': 'Saved Cities',
                'db_table': 'saved_cities',
            },
        ),
    ]
