# Generated by Django 6.1 on 2026-08-22 05:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destinations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='savedcity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_cities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='savedcity',
            constraint=models.UniqueConstraint(fields=('user', 'city'), name='uq_saved_city_user_city'),
        ),
    ]
