# Generated by Django 6.1 on 2026-08-22 05:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('SIGHTSEEING', 'Sightseeing'), ('FOOD', 'Food & Dining'), ('ADVENTURE', 'Adventure'), ('CULTURE', 'Culture & History'), ('SHOPPING', 'Shopping'), ('NIGHTLIFE', 'Nightlife'), ('NATURE', 'Nature & Outdoors'), ('OTHER', 'Other')], db_index=True, default='SIGHTSEEING', max_length=20)),
                ('duration_minutes', models.PositiveIntegerField(default=60, help_text='Estimated duration in minutes.')),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('image', models.URLField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Activity',
                'verbose_name_plural': 'Activities',
                'db_table': 'activities',
                'ordering': ['city', 'category', 'name'],
            },
        ),
    ]
