# Generated by Django 6.1 on 2026-08-22 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0001_initial'),
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='destinations.city'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['city', 'category'], name='idx_activity_city_cat'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['estimated_cost'], name='idx_activity_cost'),
        ),
    ]
