# Generated by Django 6.1 on 2026-08-22 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('budget', '0001_initial'),
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='trips.trip'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['trip', 'category'], name='idx_expense_trip_cat'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['trip', 'expense_date'], name='idx_expense_trip_date'),
        ),
        migrations.AddConstraint(
            model_name='expense',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='ck_expense_amount_non_negative'),
        ),
    ]
